//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadProLimp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int id { get; set; }
        public int idcompra { get; set; }
        public int idproducto { get; set; }
        public decimal cantidadC { get; set; }
        public decimal precioUnitarioC { get; set; }
        public decimal subtotalCompra { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
