//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadProLimp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int id { get; set; }
        public int idunidadMedida { get; set; }
        public int idproveedor { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string categoria { get; set; }
        public decimal precioUnitario { get; set; }
        public int stock { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public System.DateTime fechaUltimaCompra { get; set; }
        public decimal precioCompra { get; set; }
        public int cantidadMinimaStock { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
